site_name: mkdocs-playground
repo_url: https://github.com/axemanofic/mkdocs-playground
repo_name: axemanofic/mkdocs-playground
theme:
  name: material
  custom_dir: ./docs/overrides
  logo: assets/logo.svg
  favicon: assets/logo.ico
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: catppuccin-latte
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: catppuccin-mocha
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search
  - tags
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_root_heading: true
            show_if_no_docstring: true
            inherited_members: true
            members_order: source
            separate_signature: true
            unwrap_annotated: true
            filters:
              - '!^_'
            merge_init_into_class: true
            docstring_section_style: spacy
            signature_crossrefs: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_source: false
extra:
  social:
    - icon: material/github
      link: https://github.com/axemanofic/mkdocs-playground
      name: Github
    - icon: material/language-python
      link: https://pypi.org/project/clite/
      name: PyPi
    - icon: material/twitter
      link: https://x.com/axemanofic
    - icon: material/linkedin
      link: https://www.linkedin.com/in/axemanofic/
copyright: Copyright &copy; 2025 Roman Sotnikov
extra_css:
  - stylesheets/extra.css
