site_name: mkdocs-playground
repo_url: https://github.com/axemanofic/mkdocs-playground
repo_name: axemanofic/mkdocs-playground
theme:
  name: material
  custom_dir: ./docs/overrides
  logo: assets/logo.svg
  favicon: assets/logo.ico
  features:
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: catppuccin-latte
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: catppuccin-mocha
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search
  - tags
extra:
  social:
    - icon: material/github
      link: https://github.com/axemanofic/mkdocs-playground
      name: Github
    - icon: simple/pypi
      link: https://pypi.org/project/clite/
      name: PyPi
copyright: Copyright &copy; 2025 Roman Sotnikov
extra_css:
  - stylesheets/extra.css
