site_name: mkdocs-playground
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg
  features:
    - navigation.tracking
    - navigation.top
    - content.code.copy
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to dark 77  mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: catppuccin-latte
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: catppuccin-mocha
      toggle:
        icon: material/weather-night
        name: Switch to system mode
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search
  - tags
extra:
  social:
    - icon: material/github
      link: https://github.com/axemanofic/mkdocs-playground
      name: Github
    - icon: simple/pypi
      link: https://pypi.org/project/dj-raw-sql/
      name: PyPi
copyright: Copyright &copy; 2023 Roman Sotnikov
extra_css:
  - stylesheets/extra.css
