[project]
name = "mkdocs-playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "mkdocs-material>=9.6.9",
    "mkdocstrings-python>=1.16.5",
]
