name: Build and deploy package
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install caching
        uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Install mkdocs
        run: pip install mkdocs-material
      - name: Deploy documentation
        run: mkdocs gh-deploy --force
