name: Build and deploy package
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install caching
        uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Install mkdocs
        run: pip install mkdocs-material
      - name: Deploy documentation
        run: mkdocs gh-deploy
